name: RSpec

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  pytest:
    name: Run pytest
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker Build
        run: docker-compose build
      - name: Docker Compose Up
        run: docker-compose up -d
      - name: create db
        run: docker-compose run web rails db:create
      - name: Run RSpec
        run: docker-compose exec web rspec
